links = [
    {"name": "Arrays", "url": "/lessons/1", "lesson_id": 1},
    {"name": "Linked Lists", "url": "/lessons/2", "lesson_id": 2},
    {"name": "Stacks", "url": "/lessons/3", "lesson_id": 3},
    {"name": "Queues", "url": "/lessons/4", "lesson_id": 4},
    {"name": "Hash Tables", "url": "/lessons/5", "lesson_id": 5},
    {"name": "Trees", "url": "/lessons/6", "lesson_id": 6},
    {"name": "Graphs", "url": "/lessons/7", "lesson_id": 7},
    {"name": "Heaps", "url": "/lessons/8", "lesson_id": 8},
    {"name": "Tries (Prefix Trees)", "url": "/lessons/9", "lesson_id": 9},
    {"name": "Sorting Algorithms", "url": "/lessons/10", "lesson_id": 10},
    {"name": "Searching Algorithms", "url": "/lessons/11", "lesson_id": 11},
    {"name": "Dynamic Programming", "url": "/lessons/12", "lesson_id": 12},
    {"name": "Greedy Algorithms", "url": "/lessons/13", "lesson_id": 13},
    {"name": "Divide and Conquer", "url": "/lessons/14", "lesson_id": 14},
    {"name": "Backtracking", "url": "/lessons/15", "lesson_id": 15},
    {"name": "Graph Algorithms", "url": "/lessons/16", "lesson_id": 16},
    {"name": "Recursive Algorithms", "url": "/lessons/17", "lesson_id": 17},
    {"name": "String Algorithms", "url": "/lessons/18", "lesson_id": 18},
]
